version: '3.8'
services:
  api:
    image: node:18
    working_dir: /app
    volumes:
      - ./apps/api:/app
    ports:
      - "3333:3333"
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm run db:init && npm start"

  web:
    image: node:18
    working_dir: /app
    volumes:
      - ./apps/web:/app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: bash -c "npm install && npm start"
