name: Playwright Integration Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Docker up
      run: ls;docker-compose up
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Wait for web
      run: chmod +x wait-for-it.sh; ./wait-for-it.sh localhost:3333 -t 300
    - name: Wait for api
      run: ./wait-for-it.sh localhost:8080 -t 300
    - name: Run tests
      run: npx playwright test
    # - uses: actions/upload-artifact@v3
    #   if: always()
    #   with:
    #     name: Report
    #     path: test-results
    #     retention-days: 2