name: Playwright Integration Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Install api dependencies
      run: cd apps/api; npm install
    - name: Install web dependencies
      run: cd apps/web; npm install
    - name: Intal
      run: cd apps/web; npm install
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Report
        path: test-results
        retention-days: 2